services:
  - type: web
    name: digital-e-gram-panchayat-server
    env: node
    region: singapore
    plan: free
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 5000
    disk:
      name: uploads
      mountPath: /opt/render/project/src/server/uploads
      sizeGB: 1

  - type: web
    name: digital-e-gram-panchayat-client
    env: node
    region: singapore
    plan: free
    buildCommand: cd client && npm install && npm run build
    startCommand: cd client && npm run preview
    envVars:
      - key: NODE_VERSION
        value: 18.x
      - key: VITE_API_URL
        value: https://digital-e-gram-panchayat-server.onrender.com/api 